# Module: php_fpm
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.8/metricbeat-module-php_fpm.html

- module: php_fpm
  metricsets:
    - pool
  #  - process
  enabled: true
  period: 10s
  status_path: "php-status"
  hosts: ["http://127.0.0.1:81"]
  #username: "user"
  #password: "secret"
