version: '3.0'
services:
  php-fpm:
    build:
      context: ../../services/php
      args:
        - PHP_VER=7.3-fpm # php版本
        - SWOOLE_VER=4.4.5 # swoole版本
        - COMPOSER_URL=https://mirrors.aliyun.com/composer/ # composer源url
    ports:
      - "9000:9000"
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    volumes:
      - ../../app/php:/data/www:rw
      - ../../logs/php:/var/log/php:rw
      - ../../services/php/php.ini:/usr/local/etc/php/php.ini:ro # 当前php配置文件；可以拷贝修改php-dev.ini为想要的配置
      - ../../services/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
    networks:
      - nmpr
    restart: always
    command: php-fpm

  nginx:
    build:
      context: ../../services/nginx
      args:
        - NGINX_VER=1.17
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ../../app/php:/data/www:rw
      - ../../logs/nginx:/var/log/nginx
      - ../../services/nginx/conf.d:/etc/nginx/conf.d:ro
      - ../../services/nginx/certs/:/etc/nginx/certs
      - ../../services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nmpr
    restart: always
    command: nginx -g 'daemon off;'

  mysql-db:
    build:
      context: ../../services/mysql
      args:
        - MYSQL_VER=8.0
    ports:
      - "3306:3306"
    volumes:
      - ../../data/mysql:/var/lib/mysql:rw
      - ../../logs/mysql:/var/lib/mysql-logs:rw
      - ../../services/mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: 5eNyj6Nf # root密码 自行修改
      MYSQL_DATABASE: rageframe # 数据库名
      MYSQL_USER: test # 子账号
      MYSQL_PASSWORD: 2589632147 # 子密码
    networks:
      - nmpr
    restart: always
    command: "--character-set-server=utf8mb4"

  redis-db:
    build:
      context: ../../services/redis
      args:
        - REDIS_VER=5
    ports:
      - "6379:6379"
    volumes:
      - ../../services/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ../../data/redis:/data:rw
      - ../../logs/redis:/var/log/:rw
    networks:
      - nmpr
    restart: always

networks:
  nmpr:
    # driver: bridge
