version: '3.0'
services:
  metricbeat : # 相关文档 https://hub.docker.com/_/metricbeat
    build:
      context: .
      args:
        - METRICBEAT_VER=7.3.2 # 版本需要和es保持一致
    volumes:
      - ../../logs/metricbeat/:/usr/share/metricbeat/logs/
      - ../../data/metricbeat/:/usr/share/metricbeat/data
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./modules.d:/usr/share/metricbeat/modules.d
    network_mode: host
    restart: always